# Generated by Django 4.1 on 2023-03-29 05:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('text', models.TextField(default=None)),
                ('char', models.CharField(default=None, max_length=4096)),
                ('binary', models.BinaryField(default=None)),
                ('boolean', models.BooleanField(default=False)),
            ],
        ),
    ]
