#version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      DJANGO_SETTINGS_MODULE: Base.settings
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  redoc:
    build:
      context: ../redoc/config/docker
    environment:
      REDOC_OPTIONS: ""
      SPEC_URL: 'http://localhost:8000/api/schema/'
    ports:
      - "8001:80"

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      URL: 'http://localhost:8000/api/schema/'
      SERVERS: 'http://localhost:8000/'
    ports:
      - "8002:8080"

  postgres:
    image: postgres:15
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine

volumes:
  database:
